# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

## Minecraft / Forge
minecraft_version=1.21.7
minecraft_version_range=[1.21.7,1.22)
forge_version=57.0.0
forge_version_range=[57,)
loader_version_range=[57,)

## Mappings
mapping_channel=official
mapping_version=1.21.7

## Mod Properties
mod_id=onlypaxel
mod_name=OnlyPaxel
mod_license=All Rights Reserved
mod_version=1.21.7-0.2
mod_group_id=com.blocklegend001
mod_authors=Block_Legend001
mod_description=A multitool which combines pickaxe, axe and shovel