# Gradle
org.gradle.jvmargs=-Xmx6G

## Fabric Properties
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.2
loader_version=0.17.3
loom_version=1.11-SNAPSHOT
fabric_version=0.135.0+1.21.10

## Mod Properties
mod_version=1.21.10-0.2
maven_group=com.blocklegend001
archives_base_name=OnlyPaxel

## Dependencies
# rei_version=19.0.806