# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

## Minecraft / Forge
minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.22)
forge_version=54.0.10
forge_version_range=[54,)
loader_version_range=[54,)

## Mappings
mapping_channel=official
mapping_version=1.21.4

## Mod Properties
mod_id=onlypaxel
mod_name=OnlyPaxel
mod_license=All Rights Reserved
mod_version=1.21.4-0.3
mod_group_id=com.blocklegend001
mod_authors=Block_Legend001
mod_description=A multitool which combines pickaxe, axe and shovel